### ISSUE TITLE
Missing testbenches

### ISSUE THREAD

**Issue by LarsAsplund** [openpower-cores/a2i#2]
I would like to see your testbenches being provided. Without them it will be difficult to create pull requests knowing that the proposed changes will work. Are you intention to open source the tests?

**Comment by mikey** [comment]
This is something we are discussing but we don't have anything to release as yet.

A port of https://github.com/antonblanchard/simple_random to a2i is also we've considered.

**Comment by openpowerwtf** [comment]
There is a [repo](https://github.com/openpower-cores/a2-code) for build scripts and code.  Any validation tests can be put there.
