### ISSUE TITLE
L1 cache interface

### ISSUE THREAD

**Issue by darwin964** [openpower-cores/a2i#26]
Hi，in order to implement L2 cache,  we want to make an block level testbench contain L1 and L2 cache，how could I get the L1 interface? or get L1 rtl block?

**Comment by openpowerwtf** [comment]
The L1 I/D caches are part of the core rtl.

This is the spec for the core interface:
[A2L2 Spec](https://github.com/openpower-cores/a2i/blob/master/rel/doc/A2L2.pdf)

**Comment by darwin964** [comment]
@openpowerwtf Is A2 designed by full custom?

**Comment by openpowerwtf** [comment]
No, I don't think any of the random logic was custom.

**Comment by darwin964** [comment]
thanks

**Comment by openpowerwtf** [comment]
Don't forget  - BlueGene ran at a slow frequency to balance system power/perf.  Would have to synthesize to real technology today to see what the critical paths are; very likely some are around arrays.
