### ISSUE TITLE
Assistance Required in building A2I core in Vivado Windows

### ISSUE THREAD

**Issue by KrishnanRaghavan** [openpower-cores/a2i#38]
When it comes to building of the a2i core on vivado on windows machine ( I did look at the video uploaded for IBM a2i core and tried to follow the same steps on the windows machine). I tried to the following steps in windows.
 VIVADO->TCL CONSOLE and run the tcl script for IP's mentioned(reverserator32,reverserator 64..,) to build the core and save the project in a folder say(ip_repo).
Now when I try to run create_a2x_project.tcl and then fixup_a2x_bd.tcl nothing really comes up.
Requesting your assistance on this.

**Comment by openpowerwtf** [comment]
I think for windows you should first ensure the directory structure is OK.  Are the symbolic links correct?  If not, you have to correct them, or rearrange the structure and update scripts for windows-friendly environment.
