### ISSUE TITLE
build and run videos are no longer available

### ISSUE THREAD

**Issue by phonovision** [openpower-cores/a2i#46]
Video files linked in [/rel/doc/a2_build_video.md](https://github.com/openpower-cores/a2i/blob/master/rel/doc/a2_build_video.md) and [/rel/doc/a2_run_video.md](https://github.com/openpower-cores/a2i/blob/master/rel/doc/a2_run_video.md) are no longer available.

**Comment by openpowerwtf** [comment]
This is a duplicate (for same reason) of https://github.com/openpower-cores/a2o/issues/16:

> Thanks - will get that fixed up once the repo is moved. FYI - it is just showing the same steps as is listed in the readme.

If you have problems, let us know...
